language: js
version: 0.1.0

platform:
  - target: ubuntu
    version: 14.04
    arch: i686

install:
  -  npm install

api: 0.7.5

package:
  - app.js
  - musicapp.js
  - routes/index.js
  - routes/helpers/gtconfig.js
  - routes/helpers/marvin_client.js
  - routes/helpers/user-settings.js
  - views/error.hjs
  - bin/www 
  - conf/AppSettings.json
  - locales/en-GB/messages.pot
  - locales/it-IT/messages.pot 
  - package.json
  - music/Luigi/Pop/Carla Bruni - Quelquun ma dit.mp3
  - music/Luigi/Pop/C.W. - Stoneking.mp3
  - music/Luigi/Pop/Chris DeBurgh - Lady In Red.mp3
  - music/Luigi/Rock/Koop - Koop Island Blues (Official).mp3
  - music/Luigi/Rock/Litanie Des Saints - Dr. John.mp3
  - music/Luigi/Rock/Macy Gray - Beauty In The World.mp3
